# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: thalfemp <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/11/10 11:21:19 by thalfemp          #+#    #+#              #
#    Updated: 2019/11/14 14:28:06 by thalfemp         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = fdf
SRC = ch.c

all: $(NAME)

$(NAME):
		cc -I /usr/local/include $(SRC) -L /usr/local/lib -lmlx -framework OpenGL -framework AppKit
